### ISSUE TITLE
Retrieve subscription stats

### ISSUE THREAD

**Issue by taojang** [i-am-the-slime/purescript-cloud-juice#4]
Nakadi provides API to get stats of a subscription, the documentation is [here](https://nakadi.io/manual.html#/subscriptions/subscription_id/stats_get).

This ticket is about adding data type and function to support this functionality.

**Comment by i-am-the-slime** [comment]
I think we have the data type part down:
https://github.com/i-am-the-slime/purescript-cloud-juice/blob/master/src/Nakadi/Types.purs#L255-L265

**Comment by taojang** [comment]
I just realized that :laughing:

**Comment by taojang** [comment]
won't do
